### PR TITLE
Fix Child Process not working for BGREWRITEAOF on MacOS + Logging Improvements

### PR DESCRIPTION
**Pull request by KaviiSuri**
This PR fixes BGREWRITEAOF failing completely, Specifically for MacOS for now .

The root cause is that macos doesn't set `pid` to `0` for child process

The solution is to record get original pid of main process and do `isChild := syscall.Getppid() == originalPID`. The `pid == 0` check is unreliable and breaks on maocs m2 in my testing.

This PR also adds logging features and a bit of refactoring to reuse code and allow for `logger.With(...attrs)` to be logged correctly

### CODE REVIEW

**Comment by KaviiSuri** [comment]
@lucifercr07 @vinitparekh17 could you review the changes here?

**Comment by JyotinderSingh** [comment]
Please rebase on the latest master

**Comment by KaviiSuri** [comment]
@JyotinderSingh , done

**Comment by KaviiSuri** [comment]
@JyotinderSingh are there any blockers to merge this? Any effort required from my end?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh are there any blockers to merge this? Any effort required from my end?

Reviewing this

**Review by lucifercr07 — APPROVED** [review]
Thanks @KaviiSuri for fixing this, validated locally works fine in single threaded mode.
Can you please point to doc where you found this Macos M2 behaviour, wasn't able to find any concrete documentation around this behaviour.

**Comment by KaviiSuri** [comment]
@lucifercr07 i couldn't find the exact docs, but i did find a lot of people facing the same issue: https://news.ycombinator.com/item?id=19622758

also, apparently, both implementations of golang and python had to deal with such peculiarities on MacOS

**Comment by JyotinderSingh** [comment]
Thank you for these changes.

**Pull request merged**
