### PR TITLE
Adds support for JSON.RESP command

### LINKED ISSUE #500: Add support for command `JSON.RESP`
Add support for the `JSON.RESP` command in DiceDB similar to the [`JSON.RESP` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

### PR DESCRIPTION
**Pull request by lbihani9**
Resolves #500
- [x] Added support for `JSON.RESP`
- [x] Added unit tests
- [ ] Added Integrate tests
- [ ] Benchmark

Screenshot 2024-09-12 at 7 51 27 PM

https://github.com/user-attachments/assets/d497a820-f613-4466-90b5-96d25faaa695

### CODE REVIEW

**Comment by JyotinderSingh** [comment]
Please add integration and unit tests for this command.

**Comment by lbihani9** [comment]
> Please add integration and unit tests for this command.

Tests added in `eval_test.go` are unit tests, right?

**Comment by JyotinderSingh** [comment]
> > Please add integration and unit tests for this command.
> 
> 
> 
> Tests added in `eval_test.go` are unit tests, right?

Yes, missed them. Please add integration tests.

**Comment by JyotinderSingh** [comment]
There are build failures too, please fix that.

**Comment by lbihani9** [comment]
> There are build failures too, please fix that.

Locally it was working fine. Any pointers as to why they are undefined while building here? It's coming from `JSON.SET command` and I haven't updated anything there.
Screenshot from 2024-09-16 16-31-27

**Comment by JyotinderSingh** [comment]
> > There are build failures too, please fix that.
> 
> Locally it was working fine. Any pointers as to why they are undefined while building here? It's coming from `JSON.SET command` and I haven't updated anything there. Screenshot from 2024-09-16 16-31-27

Please rebase your branch on the latest master, it may fix the issues.

**Comment by lbihani9** [comment]
@JyotinderSingh, I don't think I'll be able to complete this task on time. I'm not finding enough time to work on it. Please unassign this task from me.

**Pull request closed without merging**
