### PR TITLE
FIX: Delete Command with 0 Arguments

### PR DESCRIPTION
**Pull request by vanshavenger**
#984 

Screenshot 2024-10-06 at 10 32 58 PM

### CODE REVIEW

**Comment by vanshavenger** [comment]
@lucifercr07 kindly review, Also Updating Docs of DEL

**Review by lucifercr07 — CHANGES_REQUESTED** [review]
Can you please add integration test for this.
Thanks for contributing.

**Comment by lucifercr07** [comment]
@vanshavenger what I mean was to add a integration test for this case in `integration_tests/commands/async/del_test.go`

**Comment by vanshavenger** [comment]
@lucifercr07 Added sirr

**Review by lucifercr07 — APPROVED** [review]

**Comment by vanshavenger** [comment]
@lucifercr07 kindly check PR for the Docs too, I updated it for the changes and missing things

**Pull request merged**
