### PR TITLE
test EXPIREAT

### PR DESCRIPTION
**Pull request by jh2310**

### CODE REVIEW

**Comment by raknay** [comment]
Please add description to the PR.

**Comment by raknay** [comment]
Please add unit tests. Please refer `core/eval.go`.

**Comment by jh2310** [comment]
> 请添加单元测试。请参阅`core/eval.go`。

expireat_test.go
func TestEvalEXPIREAT(t *testing.T)

**Comment by jh2310** [comment]
issue 283

**Comment by JyotinderSingh** [comment]
This feature was added in #338.

**Pull request closed without merging**
