### PR TITLE
fix: modify the config default value keep consistency

### PR DESCRIPTION
**Pull request by jujiale**
this is a config style optimize, nothing to do with core logic.
In config.go
there are some configs have  default value, such as  the following port **8082** and **8379**
`

          type http struct {
	      Enabled bool `config:"enabled" default:"true"`
	      Port    int  `config:"port" default:"8082" validate:"number,gte=0,lte=65535"`
      }
      
      type websocket struct {
	      Enabled                 bool          `config:"enabled" default:"true"`
	      Port                    int           `config:"port" default:"8379" validate:"number,gte=0,lte=65535"`
	      MaxWriteResponseRetries int           `config:"max_write_response_retries" default:"3" validate:"min=0"`
	      WriteResponseTimeout    time.Duration `config:"write_response_timeout" default:"10s"`
      }

`

but in cli.go the default value is not the same, such as  the following port **7380** and **7381**
`

        flag.IntVar(&flagsConfig.HTTP.Port, "http-port", 7380, "port for accepting requets over HTTP")
	    flag.BoolVar(&flagsConfig.HTTP.Enabled, "enable-http", false, "enable DiceDB to listen, accept, and process HTTP")

	    flag.IntVar(&flagsConfig.WebSocket.Port, "websocket-port", 7381, "port for accepting requets over WebSocket")

`

this pr only keep them the same so that default config value keep consistency.

### CODE REVIEW

**Comment by jujiale** [comment]
I think the test case failed has nothing to do with this pr, please have a check, thanks.

**Comment by piyushhhxyz** [comment]
@jujiale sync latest changes, should be solved.

**Comment by jujiale** [comment]
> @jujiale sync latest changes, should be solved.

done

**Review by lucifercr07 — APPROVED** [review]
LGTM

**Pull request merged**
