### PR TITLE
fix: issue #1114 handling negative offset in SETBIT

### PR DESCRIPTION
**Pull request by Yashasv-Prajapati**
This PR closes issue #1114 and does the following:

1. Handle negative offset values in SETBIT command.
2. Throw appropriate error (offset value out of range error) on providing negative offset.
3. Test cases added for the command with expected outcome added.

### CODE REVIEW

**Comment by Yashasv-Prajapati** [comment]
@JyotinderSingh  @lucifercr07  @apoorvyadav1111  @AshwinKul28  @soumya-codes 
Requesting you to review this PR.

**Comment by apoorvyadav1111** [comment]
Hi,

Issue #1017 is the parent issue for this PR. Please rebase the branch once #1017 is closed.

Thanks,
Apoorv

**Comment by arpitbbhayani** [comment]
Hello @apoorvyadav1111,

There has been no activity on this issue for the past 5 days.
It would be awesome if you keep posting updates to this issue so that we know you are actively working on it.

We are really eager to close this issue at the earliest, hence if we continue to see the inactivity, we will have to reassign the issue to someone else. We are doing this to ensure that the project maintains its momentum and others are not blocked on this work.

Just drop a comment with the current status of the work or share any issues you are facing. We can always chip in to help you out.

Thanks again.

**Comment by apoorvyadav1111** [comment]
Hi @Yashasv-Prajapati , please rebase this to latest master as #1017  is now closed, this is ready to be closed. Thanks

**Pull request closed without merging**
