### PR TITLE
#825: audited and made SDIFF docs consistent | added build fail fix ( Echo doc error )

### PR DESCRIPTION
**Pull request by rishavvajpayee**
## changes

This PR updates the documentation for the SDIFF command in DiceDB to improve clarity, consistency, and structure. Key changes include: ( this takes reference from the SET documentation )

 - The return values and Parameters are replaced with a detailed conditions table for successful and error scenarios and paramters with types.
 - Commands written in examples are now displayed in the bash instead of plan text. with defined`127.0.0.1:7379>` as prefix.
 - Overall structure and headings were audited to match the flow of SET Documentation
 - The build error in Echo due to `InvalidContentEntryFormatterError` was resolved. Added 'the' before teh `ECHO` as a fix. Any other changes in the Echo files were due to formatter.

### CODE REVIEW

**Comment by lucifercr07** [comment]
@rishavvajpayee please resolve conflicts

**Review by JyotinderSingh — APPROVED** [review]
Thanks for the fixes and contributions @rishavvajpayee! LGTM.

**Comment by rishavvajpayee** [comment]
i see that @JyotinderSingh merged master into my branch. I see no conflicts @lucifercr07. But i see the build failing due to tests failing.

**Comment by JyotinderSingh** [comment]
> i see that @JyotinderSingh merged master into my branch. I see no conflicts @lucifercr07. But i see the build failing due to tests failing.

unrelated test failure.

**Pull request merged**
