### PR TITLE
#484: feat: add support for command [JSON.ARRLEN]

### PR DESCRIPTION
**Pull request by jujiale**
hello:
this pr is link  #484 

add json.arrlen command. refer to redis [json.arrlen](https://redis.io/docs/latest/commands/json.arrlen/)
add unit tests in eval_test.go

because JSON.ARRLEN never change the json value, so I think there is no need to add integration test in tests/json_test.go

the json.arrlen in redis behavior as below:
`

    127.0.0.1:6379> JSON.SET user $ '{"age":13,"high":1.60,"pet":null,"language":["python","golang"],"flag":false,"partner":{"name":"tom","language":["rust"]}}'
    OK
    127.0.0.1:6379> JSON.ARRLEN user
    (error) ERR Path '.' does not exist or not an array
    127.0.0.1:6379> JSON.ARRLEN user $
    1) (nil)
    127.0.0.1:6379> JSON.ARRLEN user $.*
    1) (nil)
    2) (nil)
    3) (nil)
    4) (integer) 2
    5) (nil)
    6) (nil)
    127.0.0.1:6379> JSON.ARRLEN user $..language
    1) (integer) 2
    2) (integer) 1
    127.0.0.1:6379> JSON.ARRLEN user
    (error) ERR Path '.' does not exist or not an array

`

in dice, keep consistent

### CODE REVIEW

**Comment by jujiale** [comment]
@JyotinderSingh
hello. in dice test workflow. I find that TestExecuteQueryWithIncompatibleTypes/NullValue sometimes it result failed,as this pr run test failed. 
I test in my local env, there is one failed in fivetimes, please have a check. thanks.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh
> 
> hello. in dice test workflow. I find that TestExecuteQueryWithIncompatibleTypes/NullValue sometimes it result failed,as this pr run test failed. 
> 
> I test in my local env, there is one failed in fivetimes, please have a check. thanks.

I will take a look

**Comment by JyotinderSingh** [comment]
@jujiale please pull the latest changes, I have removed this test since it was irrelevant.

**Comment by jujiale** [comment]
> @jujiale please pull the latest changes, I have removed this test since it was irrelevant.
done. Thank you for your prompt reply

**Review by JyotinderSingh — APPROVED** [review]
Thanks @jujiale for adding support for `JSON.ARRLEN`! The changes look good and well tested.
LGTM.

**Pull request merged**
