### PR TITLE
#1101: Refactor evalAPPEND to handle leading zeros in value

### LINKED ISSUE #1101: Inconsistent APPEND: The Append cmd on dicedb cli isn't producing same output as redis-cli
## Steps to reproduce

1. APPEND ts "0043"
2. APPEND ts "0035"
3. GETRANGE ts 0 3
4. GETRANGE ts 4 7

## Expected output

image

The above output is coming from redis-cli

## Observed output

image

The observed output when the above set of commands when run on DiceDB

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
5. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

### PR DESCRIPTION
**Pull request by shashi-sah2003**
Fixes #1101 
evalAPPEND function wasn't configured to handle the case with leading zeros and it is treating value "0043" as "43"
I have added that case to handle it properly and producing desired result as of redis

image

### CODE REVIEW

**Comment by shashi-sah2003** [comment]
@lucifercr07 @JyotinderSingh pls review this it fixes #1101

**Review by JyotinderSingh — CHANGES_REQUESTED** [review]
Thanks for this fix, it will be good to have unit and integration tests verifying the functionality so that it doesn't break in the future.

**Comment by shashi-sah2003** [comment]
@JyotinderSingh @lucifercr07 I have added both unit test and integration_test for above append case
plss review

**Review by JyotinderSingh — APPROVED** [review]
Awesome, thanks for the fixes and tests @shashi-sah2003! LGTM

**Pull request merged**
