### PR TITLE
Added Test Cases for EXISTS, ECHO and EXPIRE with HTTP Issue #737

### PR DESCRIPTION
**Pull request by harsh082ip**
As mentioned on the issue, I've completed 2/5 of the given test cases (i.e. EXISTS and ECHO), and I'll also create PR for the remaining test cases soon

EXISTS test cases - screenshot
image

ECHO test cases - screenshot
image

### CODE REVIEW

**Comment by harsh082ip** [comment]
Hii @lucifercr07 @pratikpandey21 

Can you please review this PR, I'll create PR for the remaining test cases in the issue soon
Please let me know if any changes are required

Regards,

**Review by apoorvyadav1111 — COMMENTED** [review]
Hey, thank you for your contribution. The changes look good to me. I do not have permission to merge PR, however, one of the contributors will be picking this up for review.

**Comment by harsh082ip** [comment]
Thank you for your feedback, I'll soon create PR of the remaining test cases as well

**Comment by harsh082ip** [comment]
Update!!!
I've added test cases for EXPIRE with HTTP

image


Hii,
@apoorvyadav1111 @pratikpandey21 @arpitbbhayani @lucifercr07 

Can you please review these changes

**Comment by harsh082ip** [comment]
Hi everyone!

@apoorvyadav1111 @pratikpandey21 @arpitbbhayani @lucifercr07

I'm encountering an issue where the build checks are failing. In the logs, I’m seeing the following error:

npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/opt/build/repo/docs/package.json'

Could this be related to the integration tests or the React app setup? Or am I possibly missing something else that could be causing this?

**Comment by lucifercr07** [comment]
@harsh082ip ignore these workflows for now, if your lint and dice-test-suite builds are passing you should be fine.

**Comment by harsh082ip** [comment]
Ok @lucifercr07 ,
Thank you for clarifying

**Review by pratikpandey21 — APPROVED** [review]
Looks good. @lucifercr07 can you merge please?

**Comment by harsh082ip** [comment]
Thank you for reviewing and merging the PR, but these two test cases are pending (i.e. expireat_test.go & expiretime_test.go)

I'll create a PR related to this by tomorrow

Regards,

**Comment by harsh082ip** [comment]
#865 

Hii @apoorvyadav1111 @pratikpandey21 ,
 I've created the PR for the remaining test cases (i.e. for EXPIREAT & EXPIRETIME),
Can you please review this and let me know in case of any changes

Regards,

**Pull request merged**
