### PR TITLE
#1016 Migrated `INCR` commands

### LINKED ISSUE #1016: Command Migration: ('INCR', 'INCRBY', 'INCRBYFLOAT', 'DECR', 'DECRBY')
This issue tracks the migration of the mentioned commands - ('INCR', 'INCRBY', 'INCRBYFLOAT', 'DECR', 'DECRBY') to make them compatible across the three protocols supported by the Dice database: RESP, HTTP, and WebSocket.
DiceDB now supports more than one protocols (Resp/http/websocket). We don't want eval operation of each command to be strictly bound with any of the protocols. Currently eval function return statements of each command is bounded to the RESP protocol. 

*The migration is required because:*

- The current implementation is specific to the RESP protocol
- Evaluation functions of each command must be refactored to ensure protocol-agnostic behavior.
- Evaluation functions should return raw responses instead of protocol specific responses.

The goal is to make the command logic protocol-independent, allowing all three protocols to call the same core functionality seamlessly.

### Requirements

- Refactor the evaluation function of `[Command Name]` to be generic.
- Ensure the evaluation function does not include protocol-specific logic.

### Migration Steps

1. **Analyze Current Implementation**
   - Review the current codebase to understand how the command logic is implemented.

2. **Refactor Return Logic**
   - Create a new function with the function definition as `evalXXX(args []string, store *dstore.Store) *EvalResponse` under the file `/internal/eval/store_eval.go`
   - Analyse return statements of the eval and modify them to send raw types without encoding
   - Use errors in the return statements from `/errors/migrated_errors.go` file
   - Use perdefined responses from `/internal/clientio/resp.go` file as RespType variables

3. **Command/Worker specific Changes**
   - Make `IsMigrated` flag to true in the commands information under `/internal/eval/commands.go` file.
   - Use the newly written eval function against the `NewEval` parameter in the same command structure.
   - Delete the old eval function from the `/internal/eval/eval.go` file.
   - Add the migrated command to the `/internal/worker/CommandsMeta` map and make it's type as `SingleShard`

4. **Update Unit Tests**
   - Refactor existing unit tests to accommodate the new implementation.
   - Add new unit tests if necessary to cover all possible cases.

5. **Integration Tests**
   - Run all integration tests to ensure successful migration.
   - Ensure that each protocol (RESP, HTTP, WebSocket) works correctly after migration.

### Checklist

- [ ] Migrated the evalXXX function with the latest definition
- [ ] Update or add unit tests for the new implementation.
- [ ] All unit tests pass successfully.
- [ ] Ensure all integration tests pass successfully.

### Additional Notes

- Describe any edge cases that need to be handled in the generic function.
- Mention any protocol-specific optimizations required in wrappers.
  
If there are any questions or concerns about this migration, please mention them here.

### Related Issues/PRs

- Sample implementation for the Get, Set, GetSet and SetEx can be found in [this Pull Request.](https://github.com/DiceDB/dice/pull/766)

### PR DESCRIPTION
**Pull request by pg30**
Closes #1016

### CODE REVIEW

**Comment by apoorvyadav1111** [comment]
Hi, Thank you for making these changes.

Please add integration tests in resp, http and websocket folder. Additionally, please audit and update documentation for all the migrated commands. If this PR is still in progress, you could mark it as `Draft`, which will allow you to post update, ask questions, get pre-reviewed but not get `Changes requested`.

Thanks
Apoorv

**Comment by pg30** [comment]
Have added a new error to make the `INCRBYFLOAT` command consistent with redis.
```
	ErrInvalidFloat               = errors.New("ERR value is not a valid float")                                         // Signals that a value provided is not in a valid float format.
```

**Comment by pg30** [comment]
@apoorvyadav1111 can you pre-review this if i need to do any changes. 
Thanks

**Comment by apoorvyadav1111** [comment]
Hi @pg30 , I have checked the changes as per the checklist. I see that we are still having tests in async folder. We can migrate them to resp folder, (please use any existing test file in resp folder as reference). Additionally, we need to add tests in websocket folder too. 

I will look at the changes thoroughly once it checks off everything and is ready for review.

Thanks

**Comment by AshwinKul28** [comment]
hi @pg30 you can use ErrGeneral for the error if it's not getting used at multiple evals, no need to create a separate error for this usecase. Thanks

**Comment by pg30** [comment]
Thanks for the feedback @apoorvyadav1111 @AshwinKul28
Will make the changes accordingly

**Comment by pg30** [comment]
@AshwinKul28 can you review this pls

**Comment by pg30** [comment]
@AshwinKul28 Http and Websockets integration tests in the PR involving big integers like math.MaxInt64 and math.MinInt64 are functionally working but not logically correct due to #1163 . 
Can create a separate issue to clean up those once we fix it.

**Comment by AshwinKul28** [comment]
Hey @pg30 Thanks a lot for this commendable effort. Changes looks good. Please verify all the docs changes once whether they are aligned with the ideal document - https://github.com/DiceDB/dice/blob/master/docs/sample_command_docs.md

You can include best practices, and additional notes if required in each of these docs. 

Otherwise, the changes look great. Once docs changes are confirmed will merge the PR.

**Comment by pg30** [comment]
@AshwinKul28 Thanks for reviewing the changes. I have added alternatives section for the `INCR` and `DECR` commands. Rest of the docs looks good to me. Feel free to merge the PR

**Review by AshwinKul28 — APPROVED** [review]
Thanks. LGTM

**Pull request merged**
