### PR TITLE
Add support for arm64

### PR DESCRIPTION
**Pull request by DarkiT**
The current version of the EvalBGREWRITEAOF method does not support arm64. Add support for arm64.

### CODE REVIEW

**Review by lucifercr07 — COMMENTED** [review]
@DarkiT thanks for contributing.
I believe currently build support is only for `amd` and not for `arm`. Build [File](https://github.com/DiceDB/dice/blob/fc418bafc44dc5cf7c8321f4cad29343475e286a/.goreleaser.yaml) for reference.
 Also I'm not sure if we shall just use a `if-else` block in this case based on `runtime.GOARCH` for this function as it's leading to duplication of code and would need to maintain in both paths.
 @JyotinderSingh thoughts?

**Comment by JyotinderSingh** [comment]
@DarkiT this PR has been open for a while, would you be able to address the comments?

**Comment by JyotinderSingh** [comment]
I just read up a little more about platform-specific code, and it looks like this is the best way to handle it.

**Review by JyotinderSingh — APPROVED** [review]
Thanks for these changes @DarkiT!

**Pull request merged**
