### PR TITLE
#490: feat:add support for command [JSON.ARRTRIM]

### PR DESCRIPTION
**Pull request by jujiale**
hello:
this pr is link issue: #490 

feature: add support for command [JSON.ARRTRIM] including integration test. refer to [redis.arrtrim](https://redis.io/docs/latest/commands/json.arrtrim/)

In redis. the JSON.ARRTRIM act as below:

`

    127.0.0.1:6379> JSON.SET user $ '{"connection":{"wireless":true,"names":["a","b","c","d","e"]},"price":99.98,"stock":25,"colors":["black","silver"],"names":[0,1,2,3,4,5,6]}'
    OK
    127.0.0.1:6379> JSON.ARRTRIM user $ a 3
    (error) Couldn't parse as integer
    127.0.0.1:6379> JSON.ARRTRIM user123 $ 0 3
    (error) ERR could not perform this operation on a key that doesn't exist
    127.0.0.1:6379> JSON.ARRTRIM user $.names 1 4
    1) (integer) 4
    127.0.0.1:6379> JSON.GET user
    "{\"connection\":{\"wireless\":true,\"names\":[\"a\",\"b\",\"c\",\"d\",\"e\"]},\"price\":99.98,\"stock\":25,\"colors\":[\"black\",\"silver\"],\"names\":[1,2,3,4]}"
    127.0.0.1:6379> JSON.SET user $ '{"connection":{"wireless":true,"names":["a","b","c","d","e"]},"price":99.98,"stock":25,"colors":["black","silver"],"names":[0,1,2,3,4,5,6]}'
    OK
    127.0.0.1:6379> JSON.ARRTRIM user $..names 1 4
    1) (integer) 4
    2) (integer) 4
    127.0.0.1:6379> JSON.GET user
    "{\"connection\":{\"wireless\":true,\"names\":[\"b\",\"c\",\"d\",\"e\"]},\"price\":99.98,\"stock\":25,\"colors\":[\"black\",\"silver\"],\"names\":[1,2,3,4]}"
    127.0.0.1:6379> JSON.SET user $ '{"connection":{"wireless":true,"names":["a","b","c","d","e"]},"price":99.98,"stock":25,"colors":["black","silver"],"names":[0,1,2,3,4,5,6]}'
    OK
    127.0.0.1:6379> JSON.ARRTRIM user $.names -4 -1
    1) (integer) 4
    127.0.0.1:6379> JSON.GET user
    "{\"connection\":{\"wireless\":true,\"names\":[\"a\",\"b\",\"c\",\"d\",\"e\"]},\"price\":99.98,\"stock\":25,\"colors\":[\"black\",\"silver\"],\"names\":[3,4,5,6]}"
    127.0.0.1:6379> JSON.ARRTRIM user $.names 1 100
    1) (integer) 3
    127.0.0.1:6379> JSON.GET user
    "{\"connection\":{\"wireless\":true,\"names\":[\"a\",\"b\",\"c\",\"d\",\"e\"]},\"price\":99.98,\"stock\":25,\"colors\":[\"black\",\"silver\"],\"names\":[4,5,6]}"
    127.0.0.1:6379> JSON.ARRTRIM user $.names -3 -2
    1) (integer) 2
    127.0.0.1:6379> JSON.GET user
    "{\"connection\":{\"wireless\":true,\"names\":[\"a\",\"b\",\"c\",\"d\",\"e\"]},\"price\":99.98,\"stock\":25,\"colors\":[\"black\",\"silver\"],\"names\":[4,5]}"
    127.0.0.1:6379> JSON.ARRTRIM user $.names 4 2
    1) (integer) 0
    127.0.0.1:6379> JSON.GET user
    "{\"connection\":{\"wireless\":true,\"names\":[\"a\",\"b\",\"c\",\"d\",\"e\"]},\"price\":99.98,\"stock\":25,\"colors\":[\"black\",\"silver\"],\"names\":[]}"
    127.0.0.1:6379> JSON.SET user $ [1,2,3,4,5]
    OK
    127.0.0.1:6379> JSON.ARRTRIM user $ 2 4
    1) (integer) 3
    127.0.0.1:6379> JSON.GET user
    "[3,4,5]"
    127.0.0.1:6379> JSON.ARRTRIM user $ -100  2
    1) (integer) 3
    127.0.0.1:6379> JSON.GET user
    "[3,4,5]"

`
in diceDB, keep the same logic as redis.

### CODE REVIEW

**Comment by jujiale** [comment]
@bijuli74 hello. in testEvalHVALS/key_exists. the following logic my have different order
`

    "key exists": {
			    setup: func() {
				    key := "KEY_MOCK"
				    field := "mock_field_name"
				    field1 := "mock_field_name_1"
				    newMap := make(HashMap)
				    **newMap[field] = "mock_field_value"
				    newMap[field1] = "mock_field_value_1"**
    
				    obj := &object.Obj{
					    TypeEncoding:   object.ObjTypeHashMap | object.ObjEncodingHashMap,
					    Value:          newMap,
					    LastAccessedAt: uint32(time.Now().Unix()),
				    }
    
				    store.Put(key, obj)
			    },
			    input:  []string{"KEY_MOCK"},
			    **output: clientio.Encode([]string{"mock_field_value", "mock_field_value_1"}, false),**
		    },


`

in eval/evalHVALS
`

      func evalHVALS(args []string, store *dstore.Store) []byte {
	    if len(args) != 1 {
		    return diceerrors.NewErrArity("HVALS")
	    }
    
	    key := args[0]
	    obj := store.Get(key)
    
	    if obj == nil {
		    return clientio.Encode([]string{}, false) // Return an empty array for non-existent keys
	    }
    
	    if err := object.AssertTypeAndEncoding(obj.TypeEncoding, object.ObjTypeHashMap, object.ObjEncodingHashMap); err != nil {
		    return diceerrors.NewErrWithMessage(diceerrors.WrongTypeErr)
	    }
    
	    hashMap := obj.Value.(HashMap)
	    results := make([]string, 0, len(hashMap))
    
	    **for _, value := range hashMap {
		    results = append(results, value)
	    }**
    
	    return clientio.Encode(results, false)
    }

`

because the element is map don't have order. so the output maybe["mock_field_value", "mock_field_value_1"] or ["mock_field_value_1", "mock_field_value"]. which could result in failed when execute unittest, such as below:

image

so I modified the logic for the unittest could pass. 

as the following
`

      "key exists": {
			      setup: func() {
				      key := "KEY_MOCK"
				      field := "mock_field_name"
				      newMap := make(HashMap)
				      newMap[field] = "mock_field_value"
      
				      obj := &object.Obj{
					      TypeEncoding:   object.ObjTypeHashMap | object.ObjEncodingHashMap,
					      Value:          newMap,
					      LastAccessedAt: uint32(time.Now().Unix()),
				      }
      
				      store.Put(key, obj)
			      },
			      input:  []string{"KEY_MOCK"},
			      output: clientio.Encode([]string{"mock_field_value"}, false),
		      },

`

**Review by JyotinderSingh — APPROVED** [review]
Thanks for adding support for `JSON.ARRTRIM` command, @jujiale! The changes look good and well-tested. Only had a minor comment.

**Comment by JyotinderSingh** [comment]
> Thanks for adding support for `JSON.ARRTRIM` command, @jujiale! The changes look good and well-tested. Only had a minor comment.

It was a minor suggestion, applied it myself.

**Comment by JyotinderSingh** [comment]
> @bijuli74 hello. in testEvalHVALS/key_exists. the following logic my have different order
> 
> (please pay attention the code which ** wrapped) `
> 
> ```
> "key exists": {
> 		    setup: func() {
> 			    key := "KEY_MOCK"
> 			    field := "mock_field_name"
> 			    field1 := "mock_field_name_1"
> 			    newMap := make(HashMap)
> 			    **newMap[field] = "mock_field_value"
> 			    newMap[field1] = "mock_field_value_1"**
> 
> 			    obj := &object.Obj{
> 				    TypeEncoding:   object.ObjTypeHashMap | object.ObjEncodingHashMap,
> 				    Value:          newMap,
> 				    LastAccessedAt: uint32(time.Now().Unix()),
> 			    }
> 
> 			    store.Put(key, obj)
> 		    },
> 		    input:  []string{"KEY_MOCK"},
> 		    **output: clientio.Encode([]string{"mock_field_value", "mock_field_value_1"}, false),**
> 	    },
> ```
> 
> `
> 
> in eval/evalHVALS `
> 
> ```
>   func evalHVALS(args []string, store *dstore.Store) []byte {
>     if len(args) != 1 {
> 	    return diceerrors.NewErrArity("HVALS")
>     }
> 
>     key := args[0]
>     obj := store.Get(key)
> 
>     if obj == nil {
> 	    return clientio.Encode([]string{}, false) // Return an empty array for non-existent keys
>     }
> 
>     if err := object.AssertTypeAndEncoding(obj.TypeEncoding, object.ObjTypeHashMap, object.ObjEncodingHashMap); err != nil {
> 	    return diceerrors.NewErrWithMessage(diceerrors.WrongTypeErr)
>     }
> 
>     hashMap := obj.Value.(HashMap)
>     results := make([]string, 0, len(hashMap))
> 
>     **for _, value := range hashMap {
> 	    results = append(results, value)
>     }**
> 
>     return clientio.Encode(results, false)
> }
> ```
> 
> `
> 
> because the element is map don't have order. so the output maybe["mock_field_value", "mock_field_value_1"] or ["mock_field_value_1", "mock_field_value"]. which could result in failed when execute unittest, such as below:
> 
> image
> 
> so I modified the logic for the unittest could pass.
> 
> as the following `
> 
> ```
>   "key exists": {
> 		      setup: func() {
> 			      key := "KEY_MOCK"
> 			      field := "mock_field_name"
> 			      newMap := make(HashMap)
> 			      newMap[field] = "mock_field_value"
>   
> 			      obj := &object.Obj{
> 				      TypeEncoding:   object.ObjTypeHashMap | object.ObjEncodingHashMap,
> 				      Value:          newMap,
> 				      LastAccessedAt: uint32(time.Now().Unix()),
> 			      }
>   
> 			      store.Put(key, obj)
> 		      },
> 		      input:  []string{"KEY_MOCK"},
> 		      output: clientio.Encode([]string{"mock_field_value"}, false),
> 	      },
> ```
> 
> `

This looks good, thanks for the fix!

**Pull request merged**
