### PR TITLE
#972: fix: Fixes output of RPUSH command

### LINKED ISSUE #972: Inconsistent `RPUSH`: Command returns OK instead of Integer(length of list)
## Steps to reproduce

```
127.0.0.1:7379> RPUSH mylist 1000 2000
```

## Expected output

The expected output when the above set of commands (maybe when run on Redis)

```
127.0.0.1:6379> RPUSH mylist 1000 2000
(integer) 2
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
127.0.0.1:7379> RPUSH mylist 1000 2000
OK
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

### PR DESCRIPTION
**Pull request by Aditya-Chowdhary**
Fixes #972 by returning length instead of OK in RPUSH.

### CODE REVIEW

**Comment by kaustubhdeokar** [comment]
Hi @arpitbbhayani  @Aditya-Chowdhary,
I'm facing issue in connection of the dice cli to the live server, the live server listens to port 7379 ```("version":"0.0.4","port":7379).. and the dice cli connects to ```
and on running dice it gives this, 
```Error 111 connecting to 127.0.0.1:6379. Connection refused.```

For now i've done a hack starting docker using -p 6379:7379, which enables me to play around, but as soon as i want to write and test that code, i've to build an image which is very redundant process always.
Please help, thank you.

**Comment by Aditya-Chowdhary** [comment]
@kaustubhdeokar. The Redis server runs on port 6379, and the DiceDB Server runs on 7379. However, by default, the dice-cli connects to port 6379. You aren't able to run the cli on default mode because nothing is running on port 6379. To connect to dice-db using the cli, run `dice -p 7379`. You can run `dice --help` to see the default behaviour. Your docker hack works because you are running the running the server on 6379 using `-p 6379:6379`

**Comment by kaustubhdeokar** [comment]
Thanks a lot @Aditya-Chowdhary

**Review by apoorvyadav1111 — CHANGES_REQUESTED** [review]
Hi, Thanks for contributing to DiceDB. I have the following suggestions :
1. During the type and encoding check, I think we can remove the check for set data, as we are doing that in the next check anyway. I did some changes in the local for this PR and it was working as expected. However, please test the changes and add scenarios in the tests.
2. We can add more test cases for errors. I could not find much test cases for error, especially when the key is of type set, hmap, json, etc. 
With these suggestions I believe, we will be increasing test coverage for this command.

Thanks.

**Comment by apoorvyadav1111** [comment]
Hi @Aditya-Chowdhary , I think there was some issue with the merge/rebase; We have commits from the master branch in the PR.
Thanks
Apoorv

**Comment by JyotinderSingh** [comment]
I am not sure what is happening in this PR. The changes don't seem to be matching what is mentioned in the description.

**Comment by Aditya-Chowdhary** [comment]
Hi @apoorvyadav1111 @JyotinderSingh apologies for the confusion. I had originally made this PR to fix the output of the RPUSH command, but a duplicate PR has been merged in. As there seems to have been a problem with the rebase/merge as noted above, and as I will be unable to contribute for a couple of days, I will close this PR, and make a new one to work on the changes that had been requested above once I am free again. 

Thanks, 
Aditya.

**Pull request closed without merging**
