### PR TITLE
Adds HGET command and unit and integration tests

### PR DESCRIPTION
**Pull request by ashwaniYDV**
closes https://github.com/DiceDB/dice/issues/256

### CODE REVIEW

**Comment by JyotinderSingh** [comment]
Please rebase the PR, we just had a large change go in which might've introduced conflicts.

**Comment by arpitbbhayani** [comment]
@ashwaniYDV Just a reminder to rebase, so that we can merge this PR. Thanks for the patch.

**Comment by ashwaniYDV** [comment]
@JyotinderSingh @arpitbbhayani I am getting this error in `dice-test-suite/build` 
how should I fix this

```
*** Test I/O incomplete 1m0s after exiting.
exec: WaitDelay expired before I/O complete
FAIL	github.com/dicedb/dice/tests	139.085s
FAIL
make: *** [Makefile:21: test] Error 1
Error: Process completed with exit code 2.
```

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh @arpitbbhayani I am getting this error in `dice-test-suite/build` 
> 
> how should I fix this
> 
> 
> 
> ```
> 
> *** Test I/O incomplete 1m0s after exiting.
> 
> exec: WaitDelay expired before I/O complete
> 
> FAIL	github.com/dicedb/dice/tests	139.085s
> 
> FAIL
> 
> make: *** [Makefile:21: test] Error 1
> 
> Error: Process completed with exit code 2.
> 
> ```

This is due to some test flakiness, I'll retrigger the tests

**Comment by ashwaniYDV** [comment]
thanks @JyotinderSingh it passed now

**Comment by ashwaniYDV** [comment]
@JyotinderSingh please review

**Review by JyotinderSingh — APPROVED** [review]
Thanks for adding support for `HGET` command and improving the test coverage @ashwaniYDV! LGTM.

**Pull request merged**
