### PR TITLE
feat:add persist cmd

### PR DESCRIPTION
**Pull request by codeErrorSleep**
feat:add persist command 
issue #258

### CODE REVIEW

**Comment by srivastava-yash** [comment]
The implementation looks good to me, can you also add tests for the command

**Comment by codeErrorSleep** [comment]
@srivastava-yash Thank you for the reminder. I have added unit tests and resubmitted the code. Could you please review it?
P.S.: The current implementation is not based on interfaces, so methods like `get` cannot be mocked. 
Additionally, there are merge conflicts in the current branch that I don't have the permissions to resolve. Could you help with resolving these conflicts?

**Comment by srivastava-yash** [comment]
LGTM. @codeErrorSleep, I am not a maintainer of this project. 
Tagging @JyotinderSingh to confirm and approve

**Comment by JyotinderSingh** [comment]
@codeErrorSleep please rebase the PR on the latest master to resolve conflicts. Will review once done.

**Comment by codeErrorSleep** [comment]
@JyotinderSingh I have merged the master branch.

**Review by JyotinderSingh — APPROVED** [review]
Thanks for the contribution! Love the comprehensive tests!

**Pull request merged**
