### PR TITLE
ENH: Expand INCR command test suite with comprehensive edge cases

### PR DESCRIPTION
**Pull request by vanshavenger**
`Image Attached`

_This PR significantly expands the test coverage for the INCR command. I've added several new test cases to ensure robustness and correct behavior under various scenarios._

**New test cases include:**

1. Increment to and from max int64
Tests behavior at the upper limit of int64
Ensures proper error handling when exceeding the limit

2. Increment from min int64
Verifies correct incrementing from the lower bound of int64

3. Increment non-integer values
Checks error handling when attempting to increment floats, strings, and booleans

4. Increment non-existent key
Ensures proper initialization and incrementing of previously non-existent keys

5. Increment string representing integers
Tests correct handling of string-stored integer values

6. Increment with expiry
Verifies behavior of INCR on keys with expiration times

**Summary of Changes**

1. Added 6 new test cases to TestINCR function
2. Expanded test scenarios to cover int64 limits, type checking, and expiration
3. Improved test structure for better readability and maintenance

Screenshot 2024-09-17 at 3 59 31 PM
 #332

### CODE REVIEW

**Review by lucifercr07 — COMMENTED** [review]
LGTM, approved. Thanks for contributing @vanshavenger

**Review by lucifercr07 — APPROVED** [review]

**Comment by vanshavenger** [comment]
Thanks @lucifercr07 if there is any fix or anything else to do in this PR, let me know.

**Comment by lucifercr07** [comment]
@vanshavenger build seems to be failing, please have a look and fix it.

**Comment by vanshavenger** [comment]
Hey @lucifercr07 , integration test seems to be working locally. 
Check below screenshot.

Screenshot 2024-09-17 at 5 48 05 PM

In the Build Stage:
it is failing at these places. but when i run integration test locally these get passed.

Screenshot 2024-09-17 at 5 49 43 PM

Screenshot 2024-09-17 at 5 50 01 PM

**Comment by lucifercr07** [comment]
@vanshavenger I believe it's a flakiness issue, will look into it. Thanks.
```
json_test.go:925: assertion failed: {"a":"b","b":[{"a":2.2},{"a":5},{"a":"c"}]} (out string) != {"b":[{"a":2.2},{"a":5},{"a":"c"}],"a":"b"} (result string)
```

**Comment by vanshavenger** [comment]
Sure @lucifercr07 , After that ig we can merge this

**Comment by vanshavenger** [comment]
@JyotinderSingh  @lucifercr07  is the issue fixed?

**Comment by lucifercr07** [comment]
@vanshavenger thanks for contributing, merged.

**Pull request merged**
