### PR TITLE
Fixing flaky unit test for JSON comparisons

### PR DESCRIPTION
**Pull request by lucifercr07**
- Using `JSONEq` from [testify](https://pkg.go.dev/github.com/stretchr/testify/require#JSONEq) package for json comparisons. This would handle the ordering issues we're facing. For e.g. current test cases fails for scenarios like below where ordering of elements is changed.

`{"a":"b","b":[{"a":2.2},{"a":5},{"a":"c"}]} (out string) != {"b":[{"a":2.2},{"a":5},{"a":"c"}],"a":"b"} (result string)`

- One of the flaky builds log [here](https://productionresultssa18.blob.core.windows.net/actions-results/89060d43-0fce-4c1c-b438-727f7c4c1b7f/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text/plain&se=2024-09-17T14:27:48Z&sig=GAlQsKMGUqV2/2Vb6SQbzLwjU/eCNhNruoRZZzQ/gJM%3D&ske=2024-09-18T01:37:18Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-09-17T13:37:18Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-09-17T14:17:43Z&sv=2024-05-04)

### CODE REVIEW

**Comment by pratikpandey21** [comment]
Looks like the issue is still there.

**Comment by JyotinderSingh** [comment]
Can you attach a log with 20 runs of the test to ensure this is fixed?

**Comment by lucifercr07** [comment]
Attached logs with 20 test run cycle:
[test_flaky_json_test.txt](https://github.com/user-attachments/files/17040443/test_flaky_json_test.txt)

```
❯ grep -Fxq "FAIL" ~/Documents/Projects/prasha/DiceDB/test_flaky_json_test.txt || echo "no match found"
no match found
```

**Review by JyotinderSingh — APPROVED** [review]
Awesome, thanks for these improvements. LGTM.

**Pull request merged**
