### PR TITLE
Add support for get in set command 207

### PR DESCRIPTION
**Pull request by sanjaydev02**
This draft PR introduces support for the GET option in the SET command. When using SET with the GET option, the command now returns the previous value of the key if it exists before updating it with the new value. If the key does not exist, nil is returned, and the new value is stored. Additionally, TTL handling (e.g., EX, PX, KEEPTTL) remains functional with this update. This PR is still a work in progress, and I'm actively learning throughout the process. Apologies for the slow progress, and feedback is greatly appreciated!

### CODE REVIEW

**Comment by sanjaydev02** [comment]
@apoorvyadav1111 hi i have written test for this get option,what is the next step?

**Comment by apoorvyadav1111** [comment]
Hi, please add test in websocket, and http folder as well. Additionally, please add unit tests for this change. Please mark it as ready for review so that we are notified about any updates.

Thanks

**Comment by sanjaydev02** [comment]
@apoorvyadav1111 ok thanks

**Comment by apoorvyadav1111** [comment]
Hi @sanjaydev02 , Hope you are well.  I am interested in knowing if any pending issues or further steps are required before it can be merged.

Thank you!

Best,
Apoorv

**Comment by JyotinderSingh** [comment]
Hi @sanjaydev02, are you still working on this PR?

**Pull request closed without merging**
