### PR TITLE
[CLEANUP] remove sql and query_manager

### PR DESCRIPTION
**Pull request by apoorvyadav1111**
Hi team,

This PR removes the sql package and `watchmanager.go`.

Apoorv

### CODE REVIEW

**Review by JyotinderSingh — APPROVED** [review]
Thanks for the cleanup @apoorvyadav1111! LGTM

**Comment by JyotinderSingh** [comment]
Just noticed something.
Please also remove the following calls from store.go:
```go
	if store.queryWatchChan != nil {
		store.notifyQueryManager(k, Set, *obj)
	}
```

Also remove the queryWatchChan since it is no longer needed.

**Review by JyotinderSingh — CHANGES_REQUESTED** [review]
requested changes

**Comment by apoorvyadav1111** [comment]
Hi @JyotinderSingh , removed queryWatchChan from dicedb. Please review.

**Review by JyotinderSingh — APPROVED** [review]
LGTM

**Pull request merged**
