### PR TITLE
#222: Added Benchmark for negative number and close to MinInt64, MaxInt64

### PR DESCRIPTION
**Pull request by Vsareen0**
- Added benchmark for negative numbers and number close to MinInt64, MaxInt64
```
=== RUN   BenchmarkMinMaxEncodeDecodeInt
BenchmarkMinMaxEncodeDecodeInt
BenchmarkMinMaxEncodeDecodeInt-12       49743938                23.24 ns/op            7 B/op          1 allocs/op
PASS
ok      github.com/dicedb/dice/core/dencoding   1.396s
```

### CODE REVIEW

**Comment by Vsareen0** [comment]
Hey @JyotinderSingh / @arpitbbhayani  this test case is failing the build, I have verified on local, `TestDecodeOneNoDataRead` this one causes build to fail. if I comment this out, works expected !

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh / @arpitbbhayani  this test case is failing the build, I have verified on local, `TestDecodeOneNoDataRead` this one causes build to fail. if I comment this out, works expected ! 

Fixed, please rebase.

**Comment by Vsareen0** [comment]
Thanks for quick resolution @JyotinderSingh !

**Comment by JyotinderSingh** [comment]
I updated the benchmark structure a little for this file, could you please take a look at accordingly move this function into `dencoding_benchmark_test.go`?

**Comment by Vsareen0** [comment]
Thanks for guidance @JyotinderSingh , looks much cleaner now !

**Review by JyotinderSingh — APPROVED** [review]
Thanks for the contribution

**Pull request merged**
