### PR TITLE
#1028: feat:Command Migration('JSON.CLEAR', 'JSON.STRLRN', 'JSON.OBJLEN

### LINKED ISSUE #1028: Command Migration: ('JSON.OBJLEN', 'JSON.STRLEN', 'JSON.CLEAR')
This issue tracks the migration of the mentioned commands - ('JSON.OBJLEN', 'JSON.STRLEN', 'JSON.CLEAR') to make them compatible across the three protocols supported by the Dice database: RESP, HTTP, and WebSocket.
DiceDB now supports more than one protocols (Resp/http/websocket). We don't want eval operation of each command to be strictly bound with any of the protocols. Currently eval function return statements of each command is bounded to the RESP protocol. 

*The migration is required because:*

- The current implementation is specific to the RESP protocol
- Evaluation functions of each command must be refactored to ensure protocol-agnostic behavior.
- Evaluation functions should return raw responses instead of protocol specific responses.

The goal is to make the command logic protocol-independent, allowing all three protocols to call the same core functionality seamlessly.

### Requirements

- Refactor the evaluation function of `[Command Name]` to be generic.
- Ensure the evaluation function does not include protocol-specific logic.

### Migration Steps

1. **Analyze Current Implementation**
   - Review the current codebase to understand how the command logic is implemented.

2. **Refactor Return Logic**
   - Create a new function with the function definition as `evalXXX(args []string, store *dstore.Store) *EvalResponse` under the file `/internal/eval/store_eval.go`
   - Analyse return statements of the eval and modify them to send raw types without encoding
   - Use errors in the return statements from `/errors/migrated_errors.go` file
   - Use perdefined responses from `/internal/clientio/resp.go` file as RespType variables

3. **Command/Worker specific Changes**
   - Make `IsMigrated` flag to true in the commands information under `/internal/eval/commands.go` file.
   - Use the newly written eval function against the `NewEval` parameter in the same command structure.
   - Delete the old eval function from the `/internal/eval/eval.go` file.
   - Add the migrated command to the `/internal/worker/CommandsMeta` map and make it's type as `SingleShard`

4. **Update Unit Tests**
   - Refactor existing unit tests to accommodate the new implementation.
   - Add new unit tests if necessary to cover all possible cases.

5. **Integration Tests**
   - Run all integration tests to ensure successful migration.
   - Ensure that each protocol (RESP, HTTP, WebSocket) works correctly after migration.

### Checklist

- [ ] Migrated the evalXXX function with the latest definition
- [ ] Update or add unit tests for the new implementation.
- [ ] All unit tests pass successfully.
- [ ] Ensure all integration tests pass successfully.

### Additional Notes

- Describe any edge cases that need to be handled in the generic function.
- Mention any protocol-specific optimizations required in wrappers.
  
If there are any questions or concerns about this migration, please mention them here.

### Related Issues/PRs

- Sample implementation for the Get, Set, GetSet and SetEx can be found in [this Pull Request.](https://github.com/DiceDB/dice/pull/766)

### PR DESCRIPTION
**Pull request by jujiale**
Closes #1028
Checklist

- [x]  Migrated the evalXXX function with the latest definition

- [x]  Update or add unit tests for the new implementation.

 

- [x] All unit tests pass successfully.

 

- [x] Ensure all integration tests pass successfully.

- [x] Ensure integration tests are added for the migrated command on multi-threaded resp server.

### CODE REVIEW

**Comment by jujiale** [comment]
linked issue #1028 
the commit msg have some error, have changed

**Comment by AshwinKul28** [comment]
Awesome changes @jujiale Looks fantastic. Left few minor comments please have a look. Everything else looks good.

**Comment by jujiale** [comment]
> Awesome changes @jujiale Looks fantastic. Left few minor comments please have a look. Everything else looks good. Please rebase with the master.

done.

**Comment by jujiale** [comment]
> Awesome changes @jujiale Looks fantastic. Left few minor comments please have a look. Everything else looks good. Please rebase with the master.

@AshwinKul28 hello，could you give the comments, I didn't see any comments in this pr. because others merged other pull requests, so I have to relove the code conflict several time  >_<.

**Comment by soumya-codes** [comment]
@jujiale lets ensure that the corresponding integration tests are migrated as well.

**Comment by jujiale** [comment]
> @jujiale lets ensure that the corresponding integration tests are migrated as well. cc @AshwinKul28

done

**Comment by soumya-codes** [comment]
@jujiale we need to add the tests for the migrated commands under integration_tests/commands/resp

I have added a new item to checklist in the PR description. Please tick the same once the integration tests are added.
Please let me or Ashwin know if you have any doubts/concern.

**Comment by jujiale** [comment]
> @jujiale we need to add the tests for the migrated commands under integration_tests/commands/resp
> 
> I have added a new item to checklist in the PR description. Please tick the same once the integration tests are added. Please let me or Ashwin know if you have any doubts/concern.

get it. I will add

**Comment by jujiale** [comment]
> @jujiale we need to add the tests for the migrated commands under integration_tests/commands/resp
> 
> I have added a new item to checklist in the PR description. Please tick the same once the integration tests are added. Please let me or Ashwin know if you have any doubts/concern.

done. have added integration_test in integration_tests/commands/resp.

**Review by JyotinderSingh — APPROVED** [review]
Thanks for these amazing changes @jujiale! The changes look well written and extremely well-tested!
Thanks @soumya-codes @AshwinKul28 for the reviews.

Approved and merging

**Pull request merged**
