### PR TITLE
Closes #277 Support for COPY command

### LINKED ISSUE #277: Add support for command `COPY`
Add support for the `COPY` command in DiceDB similar to the [`COPY` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

### PR DESCRIPTION
**Pull request by srivastava-yash**
This PR adds support for COPY command. Redis creates a deep copy of objects before adding it to the db. I have done the same thing and have added DeepCopy functions to the different data structures in the codebase. I have also added tests for the deep copy functions.

### CODE REVIEW

**Comment by srivastava-yash** [comment]
There is some error in the COPY command function right now because of which the test is failing. Figuring it out and update when its fixed.

**Comment by srivastava-yash** [comment]
The PR is ready for review. After the rebase, the test `Get All Prices` TestJSONOperation(json_test.go) seems to be failing. The order of the list was different. I am not sure why are copy command changes affecting that.

**Review by JyotinderSingh — CHANGES_REQUESTED** [review]
Thanks for the changes @srivastava-yash, I have left a few comments.

Also, consider defining an interface here to avoid a switch statement inside the eval method.

```go
// Define an interface for DeepCopy, this could be done in a new file.
type DeepCopyable interface {
    DeepCopy() interface{}
}

// Implement the interface on Obj.
func (obj *Obj) DeepCopy() *Obj {
    newObj := &Obj{
        TypeEncoding:   obj.TypeEncoding,
        LastAccessedAt: obj.LastAccessedAt,
    }
    
    // All your types will continue to define the DeepCopy interface as they are doing now.
    if copier, ok := obj.Value.(DeepCopyable); ok {
        newObj.Value = copier.DeepCopy()
    } else {
        // Handle non-DeepCopyable types
        ...
    }
    
    return newObj
}

func evalCOPY(args []string) []byte {
    if len(args) < 2 {
        return Encode(errors.New("ERR wrong number of arguments for 'copy' command"), false)
    }

    sourceKey, destinationKey := args[0], args[1]
    isReplace := false

    for _, arg := range args[2:] {
        if strings.ToUpper(arg) == "REPLACE" {
            isReplace = true
            break
        }
    }

    sourceObj := Get(sourceKey)
    if sourceObj == nil {
        return Encode(errors.New("ERR no such key"), false)
    }

    if !isReplace && Get(destinationKey) != nil {
        return Encode(errors.New("ERR destination key already exists"), false)
    }

    newObj := sourceObj.DeepCopy()
    Put(destinationKey, newObj)

    return RESP_ONE
}
```

**Comment by JyotinderSingh** [comment]
One more thing you need to take care of is how the expiry works. I have the following output from a redis terminal:
```sh
127.0.0.1:6379> SET key1 "your_value"
OK
127.0.0.1:6379> EXPIRE key1 432000
(integer) 1
127.0.0.1:6379> TTL key1
(integer) 431996
127.0.0.1:6379> COPY key1 key2
(integer) 1
127.0.0.1:6379> COPY key1 key2
(integer) 0
127.0.0.1:6379> TTL key2
(integer) 431966
127.0.0.1:6379> SET key3 "another_value"
OK
127.0.0.1:6379> EXPIRE key3 86400
(integer) 1
127.0.0.1:6379> COPY key1 key3 REPLACE
(integer) 1
127.0.0.1:6379> TTL key3
(integer) 431949
```

The `COPY` command has the following behavior in relation to key expiration.

1. **Copying a Key with Expiry:**
   - When you copy a key that has an expiration set (e.g., `key1`), the expiration time is copied to the new key (e.g., `key2`) by default.

2. **Copying with the `REPLACE` Option:**
   - When using the `COPY` command with the `REPLACE` option, the destination key's (e.g., `key3`) value will be overwritten. If the original key (`key1`) has an expiry, the overwritten key (`key3`) will retain the expiry of the original key, **replacing** the previous expiry.

**Comment by JyotinderSingh** [comment]
Please fix the linter issues as well.

**Comment by JyotinderSingh** [comment]
> The PR is ready for review. After the rebase, the test `Get All Prices` TestJSONOperation(json_test.go) seems to be failing. The order of the list was different. I am not sure why are copy command changes affecting that.

This is a test flakiness issue and can be ignored.

**Comment by srivastava-yash** [comment]
> One more thing you need to take care of is how the expiry works. I have the following output from a redis terminal:
> 
> ```shell
> 127.0.0.1:6379> SET key1 "your_value"
> OK
> 127.0.0.1:6379> EXPIRE key1 432000
> (integer) 1
> 127.0.0.1:6379> TTL key1
> (integer) 431996
> 127.0.0.1:6379> COPY key1 key2
> (integer) 1
> 127.0.0.1:6379> COPY key1 key2
> (integer) 0
> 127.0.0.1:6379> TTL key2
> (integer) 431966
> 127.0.0.1:6379> SET key3 "another_value"
> OK
> 127.0.0.1:6379> EXPIRE key3 86400
> (integer) 1
> 127.0.0.1:6379> COPY key1 key3 REPLACE
> (integer) 1
> 127.0.0.1:6379> TTL key3
> (integer) 431949
> ```
> 
> The `COPY` command has the following behavior in relation to key expiration.
> 
> 1. **Copying a Key with Expiry:**
>    
>    * When you copy a key that has an expiration set (e.g., `key1`), the expiration time is copied to the new key (e.g., `key2`) by default.
> 2. **Copying with the `REPLACE` Option:**
>    
>    * When using the `COPY` command with the `REPLACE` option, the destination key's (e.g., `key3`) value will be overwritten. If the original key (`key1`) has an expiry, the overwritten key (`key3`) will retain the expiry of the original key, **replacing** the previous expiry.

Yes, this was my understanding as well. Which is why when we have REPLACE i am using Del(destinationKey) which removes its previous object and expiry and at the end I am doing the following:
`	exp, ok := getExpiry(sourceObj)
	var exDurationMs int64 = -1
	if ok {
		exDurationMs = int64(exp)
	}
	Put(destinationKey, NewObj(value, exDurationMs, sourceType, sourceEncoding))
`
Is this not right?

**Comment by srivastava-yash** [comment]
Thank you for the interface suggestion. I wanted to implement it something like that only but wasn't sure about the non DeepCopyable data structures. I have made the required changes

**Comment by JyotinderSingh** [comment]
> > One more thing you need to take care of is how the expiry works. I have the following output from a redis terminal:
> > ```shell
> > 127.0.0.1:6379> SET key1 "your_value"
> > OK
> > 127.0.0.1:6379> EXPIRE key1 432000
> > (integer) 1
> > 127.0.0.1:6379> TTL key1
> > (integer) 431996
> > 127.0.0.1:6379> COPY key1 key2
> > (integer) 1
> > 127.0.0.1:6379> COPY key1 key2
> > (integer) 0
> > 127.0.0.1:6379> TTL key2
> > (integer) 431966
> > 127.0.0.1:6379> SET key3 "another_value"
> > OK
> > 127.0.0.1:6379> EXPIRE key3 86400
> > (integer) 1
> > 127.0.0.1:6379> COPY key1 key3 REPLACE
> > (integer) 1
> > 127.0.0.1:6379> TTL key3
> > (integer) 431949
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `COPY` command has the following behavior in relation to key expiration.
> > 
> > 1. **Copying a Key with Expiry:**
> >    
> >    * When you copy a key that has an expiration set (e.g., `key1`), the expiration time is copied to the new key (e.g., `key2`) by default.
> > 2. **Copying with the `REPLACE` Option:**
> >    
> >    * When using the `COPY` command with the `REPLACE` option, the destination key's (e.g., `key3`) value will be overwritten. If the original key (`key1`) has an expiry, the overwritten key (`key3`) will retain the expiry of the original key, **replacing** the previous expiry.
> 
> Yes, this was my understanding as well. Which is why when we have REPLACE i am using Del(destinationKey) which removes its previous object and expiry and at the end I am doing the following:
> 
> ```
>         exp, ok := getExpiry(sourceObj)
> 	var exDurationMs int64 = -1
> 	if ok {
> 		exDurationMs = int64(exp)
> 	}
> 	Put(destinationKey, NewObj(value, exDurationMs, sourceType, sourceEncoding))
> ```
> 
> Is this not right?

Looks good, could you validate the expiry behavior in test cases? It will ensure future changes don't break this.

**Comment by JyotinderSingh** [comment]
Overall the implementation looks good, please resolve the merge conflict and add the above mentioned test cases.

**Comment by srivastava-yash** [comment]
@JyotinderSingh done!

**Comment by JyotinderSingh** [comment]
@srivastava-yash looks like there is a minor linter error still coming up. Could you take a look?

**Comment by srivastava-yash** [comment]
@JyotinderSingh yes, fixed it

**Review by JyotinderSingh — APPROVED** [review]
Thanks for these changes! Approved.

**Pull request merged**
