### PR TITLE
#841: docs: update `DBSIZE` docs

### PR DESCRIPTION
**Pull request by kishanhitk**
ref: #841

### CODE REVIEW

**Comment by AshwinKul28** [comment]
HI @kishanhitk Changes look good, can you please add an Error example as well if possible? thanks

**Comment by kishanhitk** [comment]
@AshwinKul28 
According to the current docs, it throws the `NOPERM` error when the current user doesn’t have the necessary permissions to run this command. 
However, I can’t seem to find any information about user permissions in the source code or the current docs.

**Comment by JyotinderSingh** [comment]
> @AshwinKul28 
> 
> According to the current docs, it throws the `NOPERM` error when the current user doesn’t have the necessary permissions to run this command. 
> 
> However, I can’t seem to find any information about user permissions in the source code or the current docs.
> 
> 

We haven't implemented permissions for this command yet. Could you please create an issue for the same? Hopefully someone will pick it up.

**Comment by kishanhitk** [comment]
@JyotinderSingh

I've removed the `NOPERM` error from the docs for now. We can proceed with merging this PR. I'll create a new PR with the `NOPERM` example once the feature is ready.

Regarding the issue for permission management for this command, you mentioned:

> We haven't implemented permissions for this command yet

I am a bit confused. Does this mean the `ACL` feature already exists in DiceDB, and we just need to extend it to cover the `DBSIZE` command? I ask because I couldn't find any references to `ACL` in the current source code or docs. Also, the `ACL` command doesn't seem to work in the current version of DiceDB.

Given this, I'm thinking we should create an issue for implementing the `ACL` feature in DiceDB as a whole, rather than specifically "Implementing permissions for `DBSIZE`." 

Let me know if I'm misunderstanding anything here.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh
> 
> I've removed the `NOPERM` error from the docs for now. We can proceed with merging this PR. I'll create a new PR with the `NOPERM` example once the feature is ready.
> 
> Regarding the issue for permission management for this command, you mentioned:
> 
> > We haven't implemented permissions for this command yet
> 
> I am a bit confused. Does this mean the `ACL` feature already exists in DiceDB, and we just need to extend it to cover the `DBSIZE` command? I ask because I couldn't find any references to `ACL` in the current source code or docs. Also, the `ACL` command doesn't seem to work in the current version of DiceDB.
> 
> Given this, I'm thinking we should create an issue for implementing the `ACL` feature in DiceDB as a whole, rather than specifically "Implementing permissions for `DBSIZE`."
> 
> Let me know if I'm misunderstanding anything here.

You are understanding this correctly, we don't currently support ACLs in dicedb. We will tackle this separately, we should create an issue for the same.

**Pull request merged**
