### PR TITLE
#1193: Add type check for string compatibility in evalAPPEND function

### LINKED ISSUE #1193: Enhancement: `Append` to support other datatypes
Hi team,

Command `Append` has recently been migrated and missed support for all available datatypes. We need to make it consistent with Redis. For more context, please go through #1095 comments and unresolved review comments. 

Requirements:

- [ ] All datatypes are supported and error handling must be consistent. 
- [ ] updating unit tests to cover new enhancement
- [ ] updating all integration test to test new enhancement
- [ ] documentation updates with new enhancement

Thanks

### PR DESCRIPTION
**Pull request by shashi-sah2003**
fixes #1193 
added type check for string compatibility as it was giving panic issue with append is used after ZADD command

### CODE REVIEW

**Comment by shashi-sah2003** [comment]
@apoorvyadav1111 pls look at this PR and review it and also let me know if there is anything more I need to check with append command

**Comment by apoorvyadav1111** [comment]
Hi @shashi-sah2003 , any update on failing tests? Please reach out to use on discord if you need any clarifications.

**Comment by shashi-sah2003** [comment]
> Hi @shashi-sah2003 , any update on failing tests? Please reach out to use on discord if you need any clarifications.

hey @apoorvyadav1111 apologies for delay. I have added the logic for append command such that it is compatible with sortedset.
pls let me know if there are any more changes you want me to do.
thanks

**Review by apoorvyadav1111 — CHANGES_REQUESTED** [review]
Hi @shashi-sah2003 , The changes look good. Could you please add tests to validate this behavior? This will ensure any future modifications do not alter this behavior. 

Thanks

**Review by apoorvyadav1111 — APPROVED** [review]
Thanks for adding tests. Approved

**Pull request merged**
