### PR TITLE
#1260: Runs CI only when source code has changes.

### LINKED ISSUE #1260: New fixes in the CI
As discussed here: https://github.com/DiceDB/dice/pull/1116#issuecomment-2455390991
I am opening a new issue for these two changes in the CI
- Conditional triggering of linting and Testing pipeline when changes are done to only .go file (This can change if the project ever changes/includes anything other than go)
- Caching setup for the linting job as well

Please make it open for all, since it's a simple change for beginners. If no one does it in a week or so.
I will make a PR against it

cc: @JyotinderSingh

### PR DESCRIPTION
**Pull request by bhima2001**
Added a condition to execute the test suite only incase there is any changes in .go files and also added a cache in linter to store the  go setup. This pr closes #1260 .

### CODE REVIEW

**Comment by JyotinderSingh** [comment]
Thanks for this change @bhima2001! Would it be possible for you to run the CI with these changes on your fork? You can then attach the logs here.

This will help us verify that this change is doing what its supposed to.

**Comment by bhima2001** [comment]
https://github.com/bhima2001/dice/actions/runs/11812884490/job/32909079862 --> These are the logs when a .go file has some changes

**Comment by bhima2001** [comment]
@JyotinderSingh If there are changes in any other file types other that .go then the test_suite job is not getting executed (expected). Please checkout the previous commits made in this branch, I have tested it out.

**Review by JyotinderSingh — APPROVED** [review]
Thanks for this improvement @bhima2001! LGTM.

**Pull request merged**
