### PR TITLE
[WIP]-Add support for COMMAND INFO command 

### PR DESCRIPTION
**Pull request by shashankdaima**
-- need to remove readme's last line.
-- will work now xD

### CODE REVIEW

**Comment by JyotinderSingh** [comment]
Please turn this PR into a draft while you work on it, and mark it ready for review once you are done.

**Comment by arpitbbhayani** [comment]
@shashankdaima please turn this PR into draft. No need to raise PR unless you are ready with the changes.

**Comment by JyotinderSingh** [comment]
Hi @shashankdaima, I was wondering if you were still working on this PR?

**Comment by shashankleanmvp** [comment]
@JyotinderSingh 
Unfortunately, I have a change of plan. feel free to contribute to this issue. I have got some work in other OSS project. Sorry, wasn't able to reply earlier.

**Pull request closed without merging**
