### PR TITLE
Add support for command GEOPOS

### PR DESCRIPTION
**Pull request by helios2003**
The PR aims to resolve issue #1249 

### Tasks
- [x] Add the support for the command.
- [x] Add the docs.
- [x] Add integration tests.
- [x] Add unit tests.

### CODE REVIEW

**Comment by helios2003** [comment]
Hi @lucifercr07, I have made a draft PR for the issue. I will update it with all the changes in the next few days.

**Comment by helios2003** [comment]
@lucifercr07, can you please review the PR? After @arpitbbhayani's recent pushes, the tests are failing now. Can you please give me some pointers on how to adapt the code to the latest master branch?

**Comment by lucifercr07** [comment]
> @lucifercr07, can you please review the PR? After @arpitbbhayani's recent pushes, the tests are failing now. Can you please give me some pointers on how to adapt the code to the latest master branch?

@helios2003 will check once. Thanks.

**Comment by helios2003** [comment]
@lucifercr07, any updates on the review process?

**Review by lucifercr07 — APPROVED** [review]
LGTM

**Comment by helios2003** [comment]
@lucifercr07, I have made the required changes.

**Pull request merged**
