### PR TITLE
#991 Config enhancement with http and websocket properties

### PR DESCRIPTION
**Pull request by vinitparekh17**
this pr includes logic grouping of config including http and websocket support with bug minor fixes

### CODE REVIEW

**Comment by vinitparekh17** [comment]
this pr supports configuration for http and websocket protocol with logical grouping of each properties.

**Comment by vinitparekh17** [comment]
#991

**Comment by JyotinderSingh** [comment]
Thanks for these changes, could you please resolve the conflicts?

**Comment by vinitparekh17** [comment]
> Thanks for these changes, could you please resolve the conflicts?

done

**Comment by vinitparekh17** [comment]
since all checks passed no need for this workflow re-run again for clean-up commit

**Comment by JyotinderSingh** [comment]
Looks like the changes again went out of sync, could you please rebase?

**Comment by vinitparekh17** [comment]
@JyotinderSingh Can you plz review this before further merge conflicts arise?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh Can you plz review this before further merge conflicts arise? 

Taking a look

**Review by JyotinderSingh — APPROVED** [review]
The changes look good, we may end up having to configure things which affect performance separately at some point. But this is fine for now.

**Pull request merged**
