### PR TITLE
#749 fix: http json response 

### LINKED ISSUE #749: Inconsistency in cmd responses via http protocol
## Why this issue should not be ignored?
- Since `DiceDB` expects input in valid JSON format, so does the client. This ensures that both the client and server can properly communicate and understand the data being transmitted.
- Using JSON as the standard format for responses allows for consistent data representation, making it easier to parse and process the information on both ends. This way developers will have freedom to use any programming lang.

## Steps to reproduce

```sh
curl --location 'http://localhost:8082/get' \
--header 'Content-Type: application/json' \
--header 'Cache-Control: no-cache' \
--data '{
    "key": "foo"
}'
```

- Issue is not limited to this cmd, it applies on all cmds ( probably )

## Expected output
```js
{
    "statusCode": "success",
    "value": null
}
// -------- or ------ 
{
    "statusCode": "success",
    "value": "bar"
}
```

### In case error
```json
{
    "statusCode": "argsError",
    "message": "ERR wrong number of arguments for 'get' command"
}
```

## Observed output

```json
"(nil)"
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

### PR DESCRIPTION
**Pull request by vinitparekh17**
resolved #749 issue

### CODE REVIEW

**Comment by vinitparekh17** [comment]
this pr handles "(nil)" by replacing it with actual json null and enhances http response struct

test is failing although it pass when it is being run individually 
build workflow is failed but test is passing when ran as
```sh
╰─➤  go test -v -race -count=1 --run TestType ./integration_tests/commands/http
```

**Comment by vinitparekh17** [comment]
> this pr handles "(nil)" by replacing it with actual json null and enhances http response struct
> 
> build workflow is failed but test is passing when ran as
> 
> ```shell
> ╰─➤  go test -v -race -count=1 --run TestType ./integration_tests/commands/http
> ```

cc @lucifercr07

**Comment by vinitparekh17** [comment]
> > this pr handles "(nil)" by replacing it with actual json null and enhances http response struct
> > build workflow is failed but test is passing when ran as
> > ```shell
> > ╰─➤  go test -v -race -count=1 --run TestType ./integration_tests/commands/http
> > ```
> 

@JyotinderSingh i would like to have your input on this little issue, please

**Comment by JyotinderSingh** [comment]
> > > this pr handles "(nil)" by replacing it with actual json null and enhances http response struct
> 
> > > build workflow is failed but test is passing when ran as
> 
> > > ```shell
> 
> > > ╰─➤  go test -v -race -count=1 --run TestType ./integration_tests/commands/http
> 
> > > ```
> 
> > 
> 
> 
> 
> @JyotinderSingh i would like to have your input on this little issue, please
> 
> 
> 
> 

The TestCommandInfo tests are failing, do you think this could have been introduced by your changes?
Haven't seen this error happen before.

**Comment by vinitparekh17** [comment]
> ```shell
> go test -v -race -count=1 --run TestType ./integration_tests/commands/http
> ```

yes it is introduced by my changes, will fix sooner

**Comment by vinitparekh17** [comment]
> > > > this pr handles "(nil)" by replacing it with actual json null and enhances http response struct
> > 
> > 
> > > > build workflow is failed but test is passing when ran as
> > 
> > 
> > > >
> > 
> > 
> > > > ╰─➤  go test -v -race -count=1 --run TestType ./integration_tests/commands/http
> > 
> > 
> > > >
> > 
> > 
> > > 
> > 
> > 
> > @JyotinderSingh i would like to have your input on this little issue, please
> 
> The TestCommandInfo tests are failing, do you think this could have been introduced by your changes? Haven't seen this error happen before.

nvm test cases fixed

**Review by JyotinderSingh — APPROVED** [review]
Thanks for these changes @vinitparekh17! LGTM.

**Pull request merged**
